#
# Module manifest for module 'Nmx.Pwsh.SavePoint'
#
# Generated by: Michael Herndon
#
# Generated on: 12/4/2020
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule           = './Nmx.Pwsh.SavePoint.psm1'

    # Version number of this module.
    ModuleVersion        = '0.1.0'

    # Supported PSEditions
    CompatiblePSEditions = @('Desktop', 'Core')

    # ID used to uniquely identify this module
    GUID                 = 'd54a373a-7797-47bd-bfcf-887d7d04533f'

    # Author of this module
    Author               = 'Michael Herndon'

    # Company or vendor of this module
    CompanyName          = 'Nerdy Mishka'

    # Copyright statement for this module
    Copyright            = '(c) Michael Herndon. All rights reserved.'

    # Description of the functionality provided by this module
    Description          = '
A powershell module for tracking save points for procedural scripts such
as device configuration changes where a task should only be invoked if
it has not completed or certain conditions have not been met.
'

    # Minimum version of the PowerShell engine required by this module
    #PowerShellVersion    = '3.0.0'

    # Name of the PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # ClrVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport    = @(
        'Get-SaveStateFileName',
        'Read-SaveState',
        'Set-SaveStateFileName',
        'Sync-SavePoint',
        'Write-SaveState'
    )

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport      = @()

    # Variables to export from this module
    VariablesToExport    = ''

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport      = @('Save-Point')

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData          = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags         = @('save', 'save-point', 'check-point', 'savepoint')

            # A URL to the license for this module.
            LicenseUri   = 'https://www.apache.org/licenses/LICENSE-2.0'

            # A URL to the main website for this project.
            ProjectUri   = 'https://github.com/nerdymishka/nerdymishka/tree/master/pwsh/Nmx.Pwsh.SavePoint/README.md'

            # A URL to an icon representing this module.
            IconUri      = 'https://raw.githubusercontent.com/nerdymishka/nerdymishka/master/pwsh/assets/logo.png'

            # ReleaseNotes of this module
            ReleaseNotes = '
0.1.0 - Initial Release
'

            # Prerelease string of this module
            # Prerelease = ''

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            # RequireLicenseAcceptance = $false

            # External dependent modules of this module
            # ExternalModuleDependencies = @()

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''
}

