// ***********************************************************************
// Assembly         : Nex.Data
// Author           : MichaelHerndon
// Created          : 12-14-2020
//
// Last Modified By : MichaelHerndon
// Last Modified On : 12-15-2020
// ***********************************************************************
// <copyright file="Permission.cs" company="Nerdy Mishka">
//     NerdyMishka © 2016 - 2020
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Nex.Data.Model
{

    /// <summary>
    /// Class Permission.
    /// </summary>
    public class Permission
    {
        /// <summary>
        /// Gets or sets the identifier, which is not autogenerated by design
        /// to enable smart enums for permissions. 
        /// </summary>
        /// <value>The identifier.</value>
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the name.
        /// </summary>
        /// <value>The name.</value>
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the roles.
        /// </summary>
        /// <value>The roles.</value>
        public HashSet<Role> Roles { get; set; }

        /// <summary>
        /// Gets or sets the groups.
        /// </summary>
        /// <value>The groups.</value>
        public HashSet<Group> Groups { get; set; }

        /// <summary>
        /// Gets or sets the users.
        /// </summary>
        /// <value>The users.</value>
        public HashSet<User> Users { get; set; }
    }
}
