version: '3.7'
services:
  nerdy-mssql:
    image: "mcr.microsoft.com/mssql/server"
    restart: always
    environment:
      SA_PASSWORD: "chang3m3N0w!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ${DOCKER_DISK}/cache/mssql:/var/opt/mssql/data
      - ${DOCKER_DISK}/log/mssql:/var/opt/mssql/log
      - ${DOCKER_DISK}/secrets/mssql:/var/opt/mssql/secrets

  nerdy-mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --secure-file-priv=NULL
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: chang3m3N0w!
      MYSQL_DATABASE: Nerdy_Test
      MYSQL_USER: nerdy_user
      MYSQL_PASSWORD: chang3m3N0w!
    volumes:
      - "${DOCKER_DISK}/etc/mysql:/etc/mysql/"
      - "${DOCKER_DISK}/cache/mysql:/var/lib/mysql:rw"
      # /docker-entrypoint-initdb.d

  nerdy-postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: chang3m3N0w!
      POSTGRES_USER: nerdy_user
      POSTGRES_DB: Nerdy_Test
    volumes: 
      - ${DOCKER_DISK}/cache/postgres:/var/lib/postgresql/data
      - ${DOCKER_DISK}/etc/postgres:/etc/postgressql
  
  nerdy-redis:
    image: "redis:alpine"
    restart: always
    command: redis-server --requirepass chang3m3N0w!
    ports:
     - "6379:6379"
    volumes:
      - ${DOCKER_DISK}/cache/redis:/var/lib/redis
      - ${DOCKER_DISK}/etc/redis:/usr/local/etc/redis/redis.conf

    environment:
     - REDIS_REPLICATION_MODE=master

  nerdy-rabbitmq:
    image: rabbitmq:3-management
    restart: always
    hostname: nerdy-rabbitmq
    volumes:
      - ${DOCKER_DISK}/etc/rabbitmq:/etc/rabbitmq
      - ${DOCKER_DISK}/cache/rabbitmq:/var/lib/rabbitmq
      - ${DOCKER_DISK}/log/rabbitmq:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672
    # admin:admin123

  nerdy-mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ${DOCKER_DISK}/cache/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: chang3m3N0w!

  nerdy-mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: 'nerdy-mongo'
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: chang3m3N0w!