version: '3.7'

services:
  mysql:
    image: mysql:8.0
    container_name: "mysql-8"
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - "MYSQL_DATABASE=${NMX_MYSQL_DB}"
      - "MYSQL_USER=${NMX_MYSQL_USER}"
      - "MYSQL_ROOT_PASSWORD=${NMX_MYSQL_ROOT_PASSWORD}"
      - "MYSQL_PASSWORD=${NMX_MYSQL_PASSWORD}"
    ports: 
      - "3306:3306"
    networks:
      backend:
        ipv4_address: ${NMX_MYSQL_IPV4}
    volumes:
      - "${NMX_DKR}/data/mysql_8:/var/lib/mysql"
      - "${NMX_DKR}/etc/mysql_8:/etc/mysql/conf.d"
      - "${NMX_DKR}/log/mysql_8:/var/log/mysql"

networks:
  backend:
    external:
      name: nmx-backend-vnet