version: "3.7"
services: 
  hello_world:
    image: hello-world:latest
    networks: 
      frontend:
        ipv4_address: ${NMX_FRONTEND_ANCHOR}
      backend:
        ipv4_address: ${NMX_BACKEND_ANCHOR}
              
networks:
  frontend: 
    name: nmx-frontend-vnet
    ipam:
      config: 
       - subnet: ${NMX_FRONTEND_SUBNET}
  backend:
    name: nmx-backend-vnet
    ipam:
      config: 
       - subnet: ${NMX_BACKEND_SUBNET}