name: dotnet-cd
on:
  push:
    branches:
      - master
      - dnet-ci

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        run: |
          git clone https://github.com/nerdymishka/nerdymishka.git --no-checkout "$GITHUB_WORKSPACE/nm-dnet"
          cd "$GITHUB_WORKSPACE/nm-dnet"
          git fetch origin
          git sparse-checkout init --cone 
          git sparse-checkout set dnet
      - name: "require-dotnet"
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
