name: dotnet-cd
on:
  push:
    branches:
      - master
      - dnet-ci

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: set:env
        run: |
          echo "GIT_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "GIT_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "GWD2=${GITHUB_WORKSPACE}/nm-${GIT_REF##*/}" >> $GITHUB_ENV
      - name: set:gwd
        run: |
          echo "GWD=${GITHUB_WORKSPACE}/nm-${GIT_BRANCH}" >> $GITHUB_ENV"
      - name: verify:env
        run: |
          echo ${GITHUB_BRANCH}
          echo ${GWD}
          echo ${GWD2}
      - name: "checkout"
        shell: pwsh
        run: |
          git clone https://github.com/nerdymishka/nerdymishka.git --branch $ENV:GIT_BRANCH `
            --single-branch --no-checkout  "$($Env:GWD)"
          Set-Location $GWD 
          git fetch origin
          git sparse-checkout init --cone 
          git sparse-checkout set dnet
          git checkout "$($Env:GIT_BRANCH)"
      - name: "require-dotnet"
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
